Add Raisin Bran
RLBot/RLBotPack pull request #326
Opened 2024-05-27 23:53 UTC by CrabbyCrab101

It's a 1v1 C# bot that I created using RedUtils. I uploaded all the files to github itself which is why there are so many commits.

2024-05-28 00:33 UTC, VirxEC requested changes
Please delete the following files and folders as they are not needed to run the bot:

- `.gitattributes`
- `Bot.pdb`
- `Loadouts/__pycache__/`
- `RedUtils.pdb`
- `__pycache__/`

2024-05-28 00:43 UTC, CrabbyCrab101 commented
I have removed those files

2024-06-02 01:10 UTC, CrabbyCrab101 reviewed
Removed junk files

2024-06-02 14:15 UTC, VirxEC approved these changes

2024-06-02 14:16 UTC, merged